// Curated list of US universities and community colleges.
// `emailDomain` must stay unique (schema constraint); it's the school's primary
// domain. Add more anytime via the admin Settings page.

export type UniversitySeed = {
  name: string;
  country: string;
  city: string;
  emailDomain: string;
};

const raw: Array<[name: string, city: string, emailDomain: string]> = [
  // ---- Ivy League & elite private ----
  ["Harvard University", "Cambridge, MA", "harvard.edu"],
  ["Massachusetts Institute of Technology", "Cambridge, MA", "mit.edu"],
  ["Yale University", "New Haven, CT", "yale.edu"],
  ["Princeton University", "Princeton, NJ", "princeton.edu"],
  ["Columbia University", "New York, NY", "columbia.edu"],
  ["University of Pennsylvania", "Philadelphia, PA", "upenn.edu"],
  ["Brown University", "Providence, RI", "brown.edu"],
  ["Dartmouth College", "Hanover, NH", "dartmouth.edu"],
  ["Cornell University", "Ithaca, NY", "cornell.edu"],
  ["Stanford University", "Stanford, CA", "stanford.edu"],
  ["Duke University", "Durham, NC", "duke.edu"],
  ["Northwestern University", "Evanston, IL", "northwestern.edu"],
  ["Johns Hopkins University", "Baltimore, MD", "jhu.edu"],
  ["University of Chicago", "Chicago, IL", "uchicago.edu"],
  ["Vanderbilt University", "Nashville, TN", "vanderbilt.edu"],
  ["Rice University", "Houston, TX", "rice.edu"],
  ["University of Notre Dame", "Notre Dame, IN", "nd.edu"],
  ["Georgetown University", "Washington, DC", "georgetown.edu"],
  ["Carnegie Mellon University", "Pittsburgh, PA", "cmu.edu"],
  ["Emory University", "Atlanta, GA", "emory.edu"],
  ["Washington University in St. Louis", "St. Louis, MO", "wustl.edu"],
  ["California Institute of Technology", "Pasadena, CA", "caltech.edu"],
  ["University of Southern California", "Los Angeles, CA", "usc.edu"],
  ["New York University", "New York, NY", "nyu.edu"],
  ["Boston University", "Boston, MA", "bu.edu"],
  ["Boston College", "Chestnut Hill, MA", "bc.edu"],
  ["Tufts University", "Medford, MA", "tufts.edu"],
  ["Northeastern University", "Boston, MA", "northeastern.edu"],
  ["Case Western Reserve University", "Cleveland, OH", "case.edu"],
  ["Tulane University", "New Orleans, LA", "tulane.edu"],
  ["Wake Forest University", "Winston-Salem, NC", "wfu.edu"],
  ["Lehigh University", "Bethlehem, PA", "lehigh.edu"],
  ["Villanova University", "Villanova, PA", "villanova.edu"],
  ["Syracuse University", "Syracuse, NY", "syr.edu"],
  ["Fordham University", "New York, NY", "fordham.edu"],
  ["Southern Methodist University", "Dallas, TX", "smu.edu"],
  ["Texas Christian University", "Fort Worth, TX", "tcu.edu"],
  ["Baylor University", "Waco, TX", "baylor.edu"],
  ["Brandeis University", "Waltham, MA", "brandeis.edu"],
  ["Rensselaer Polytechnic Institute", "Troy, NY", "rpi.edu"],
  ["Stevens Institute of Technology", "Hoboken, NJ", "stevens.edu"],
  ["University of Rochester", "Rochester, NY", "rochester.edu"],
  ["University of Miami", "Coral Gables, FL", "miami.edu"],
  ["Pepperdine University", "Malibu, CA", "pepperdine.edu"],
  ["Santa Clara University", "Santa Clara, CA", "scu.edu"],
  ["University of San Francisco", "San Francisco, CA", "usfca.edu"],
  ["Gonzaga University", "Spokane, WA", "gonzaga.edu"],
  ["Marquette University", "Milwaukee, WI", "marquette.edu"],
  ["DePaul University", "Chicago, IL", "depaul.edu"],
  ["Loyola University Chicago", "Chicago, IL", "luc.edu"],
  ["George Washington University", "Washington, DC", "gwu.edu"],
  ["American University", "Washington, DC", "american.edu"],

  // ---- University of California system ----
  ["University of California, Berkeley", "Berkeley, CA", "berkeley.edu"],
  ["University of California, Los Angeles", "Los Angeles, CA", "ucla.edu"],
  ["University of California, San Diego", "La Jolla, CA", "ucsd.edu"],
  ["University of California, Davis", "Davis, CA", "ucdavis.edu"],
  ["University of California, Irvine", "Irvine, CA", "uci.edu"],
  ["University of California, Santa Barbara", "Santa Barbara, CA", "ucsb.edu"],
  ["University of California, Santa Cruz", "Santa Cruz, CA", "ucsc.edu"],
  ["University of California, Riverside", "Riverside, CA", "ucr.edu"],
  ["University of California, Merced", "Merced, CA", "ucmerced.edu"],

  // ---- Cal State & other California public ----
  ["San Diego State University", "San Diego, CA", "sdsu.edu"],
  ["San Jose State University", "San Jose, CA", "sjsu.edu"],
  ["California State University, Long Beach", "Long Beach, CA", "csulb.edu"],
  ["California State University, Fullerton", "Fullerton, CA", "fullerton.edu"],
  ["California State University, Northridge", "Northridge, CA", "csun.edu"],
  ["San Francisco State University", "San Francisco, CA", "sfsu.edu"],
  ["California Polytechnic State University", "San Luis Obispo, CA", "calpoly.edu"],
  ["California State Polytechnic University, Pomona", "Pomona, CA", "cpp.edu"],
  ["California State University, Sacramento", "Sacramento, CA", "csus.edu"],

  // ---- Big public flagships (by state) ----
  ["University of Michigan", "Ann Arbor, MI", "umich.edu"],
  ["Michigan State University", "East Lansing, MI", "msu.edu"],
  ["Wayne State University", "Detroit, MI", "wayne.edu"],
  ["Ohio State University", "Columbus, OH", "osu.edu"],
  ["University of Cincinnati", "Cincinnati, OH", "uc.edu"],
  ["Ohio University", "Athens, OH", "ohio.edu"],
  ["Kent State University", "Kent, OH", "kent.edu"],
  ["Miami University", "Oxford, OH", "miamioh.edu"],
  ["University of Florida", "Gainesville, FL", "ufl.edu"],
  ["Florida State University", "Tallahassee, FL", "fsu.edu"],
  ["University of Central Florida", "Orlando, FL", "ucf.edu"],
  ["University of South Florida", "Tampa, FL", "usf.edu"],
  ["Florida International University", "Miami, FL", "fiu.edu"],
  ["University of Texas at Austin", "Austin, TX", "utexas.edu"],
  ["Texas A&M University", "College Station, TX", "tamu.edu"],
  ["University of Houston", "Houston, TX", "uh.edu"],
  ["Texas Tech University", "Lubbock, TX", "ttu.edu"],
  ["University of North Texas", "Denton, TX", "unt.edu"],
  ["University of Texas at Dallas", "Richardson, TX", "utdallas.edu"],
  ["University of Washington", "Seattle, WA", "uw.edu"],
  ["Washington State University", "Pullman, WA", "wsu.edu"],
  ["University of Illinois Urbana-Champaign", "Champaign, IL", "illinois.edu"],
  ["University of Illinois Chicago", "Chicago, IL", "uic.edu"],
  ["University of Wisconsin-Madison", "Madison, WI", "wisc.edu"],
  ["University of Minnesota", "Minneapolis, MN", "umn.edu"],
  ["Pennsylvania State University", "University Park, PA", "psu.edu"],
  ["University of Pittsburgh", "Pittsburgh, PA", "pitt.edu"],
  ["Temple University", "Philadelphia, PA", "temple.edu"],
  ["University of Georgia", "Athens, GA", "uga.edu"],
  ["Georgia Institute of Technology", "Atlanta, GA", "gatech.edu"],
  ["Georgia State University", "Atlanta, GA", "gsu.edu"],
  ["University of North Carolina at Chapel Hill", "Chapel Hill, NC", "unc.edu"],
  ["North Carolina State University", "Raleigh, NC", "ncsu.edu"],
  ["University of Virginia", "Charlottesville, VA", "virginia.edu"],
  ["Virginia Tech", "Blacksburg, VA", "vt.edu"],
  ["Virginia Commonwealth University", "Richmond, VA", "vcu.edu"],
  ["George Mason University", "Fairfax, VA", "gmu.edu"],
  ["University of Maryland", "College Park, MD", "umd.edu"],
  ["Rutgers University", "New Brunswick, NJ", "rutgers.edu"],
  ["University of Arizona", "Tucson, AZ", "arizona.edu"],
  ["Arizona State University", "Tempe, AZ", "asu.edu"],
  ["Northern Arizona University", "Flagstaff, AZ", "nau.edu"],
  ["University of Colorado Boulder", "Boulder, CO", "colorado.edu"],
  ["Colorado State University", "Fort Collins, CO", "colostate.edu"],
  ["University of Oregon", "Eugene, OR", "uoregon.edu"],
  ["Oregon State University", "Corvallis, OR", "oregonstate.edu"],
  ["University of Utah", "Salt Lake City, UT", "utah.edu"],
  ["Utah State University", "Logan, UT", "usu.edu"],
  ["Brigham Young University", "Provo, UT", "byu.edu"],
  ["University of Iowa", "Iowa City, IA", "uiowa.edu"],
  ["Iowa State University", "Ames, IA", "iastate.edu"],
  ["Indiana University Bloomington", "Bloomington, IN", "iu.edu"],
  ["Purdue University", "West Lafayette, IN", "purdue.edu"],
  ["University of Kansas", "Lawrence, KS", "ku.edu"],
  ["Kansas State University", "Manhattan, KS", "ksu.edu"],
  ["University of Missouri", "Columbia, MO", "missouri.edu"],
  ["University of Nebraska-Lincoln", "Lincoln, NE", "unl.edu"],
  ["University of Oklahoma", "Norman, OK", "ou.edu"],
  ["Oklahoma State University", "Stillwater, OK", "okstate.edu"],
  ["University of Kentucky", "Lexington, KY", "uky.edu"],
  ["University of Louisville", "Louisville, KY", "louisville.edu"],
  ["University of Tennessee", "Knoxville, TN", "utk.edu"],
  ["University of Memphis", "Memphis, TN", "memphis.edu"],
  ["University of Alabama", "Tuscaloosa, AL", "ua.edu"],
  ["Auburn University", "Auburn, AL", "auburn.edu"],
  ["University of Mississippi", "Oxford, MS", "olemiss.edu"],
  ["Mississippi State University", "Starkville, MS", "msstate.edu"],
  ["Louisiana State University", "Baton Rouge, LA", "lsu.edu"],
  ["University of Arkansas", "Fayetteville, AR", "uark.edu"],
  ["University of South Carolina", "Columbia, SC", "sc.edu"],
  ["Clemson University", "Clemson, SC", "clemson.edu"],
  ["West Virginia University", "Morgantown, WV", "wvu.edu"],
  ["University of Connecticut", "Storrs, CT", "uconn.edu"],
  ["University of Massachusetts Amherst", "Amherst, MA", "umass.edu"],
  ["University of New Hampshire", "Durham, NH", "unh.edu"],
  ["University of Vermont", "Burlington, VT", "uvm.edu"],
  ["University of Maine", "Orono, ME", "maine.edu"],
  ["University of Rhode Island", "Kingston, RI", "uri.edu"],
  ["University of Delaware", "Newark, DE", "udel.edu"],
  ["University of Hawaii at Manoa", "Honolulu, HI", "hawaii.edu"],
  ["University of Nevada, Las Vegas", "Las Vegas, NV", "unlv.edu"],
  ["University of Nevada, Reno", "Reno, NV", "unr.edu"],
  ["University of New Mexico", "Albuquerque, NM", "unm.edu"],
  ["University of Idaho", "Moscow, ID", "uidaho.edu"],
  ["Boise State University", "Boise, ID", "boisestate.edu"],
  ["University of Montana", "Missoula, MT", "umt.edu"],
  ["Montana State University", "Bozeman, MT", "montana.edu"],
  ["University of Wyoming", "Laramie, WY", "uwyo.edu"],
  ["University of North Dakota", "Grand Forks, ND", "und.edu"],
  ["North Dakota State University", "Fargo, ND", "ndsu.edu"],
  ["University of South Dakota", "Vermillion, SD", "usd.edu"],
  ["South Dakota State University", "Brookings, SD", "sdstate.edu"],
  ["University of Alaska Fairbanks", "Fairbanks, AK", "uaf.edu"],

  // ---- SUNY ----
  ["University at Buffalo (SUNY)", "Buffalo, NY", "buffalo.edu"],
  ["Stony Brook University (SUNY)", "Stony Brook, NY", "stonybrook.edu"],
  ["Binghamton University (SUNY)", "Binghamton, NY", "binghamton.edu"],
  ["University at Albany (SUNY)", "Albany, NY", "albany.edu"],

  // ---- HBCUs ----
  ["Howard University", "Washington, DC", "howard.edu"],
  ["Spelman College", "Atlanta, GA", "spelman.edu"],
  ["Morehouse College", "Atlanta, GA", "morehouse.edu"],
  ["Florida A&M University", "Tallahassee, FL", "famu.edu"],
  ["North Carolina A&T State University", "Greensboro, NC", "ncat.edu"],
  ["Hampton University", "Hampton, VA", "hamptonu.edu"],
  ["Tuskegee University", "Tuskegee, AL", "tuskegee.edu"],

  // ---- Community colleges (large / well-known) ----
  ["Miami Dade College", "Miami, FL", "mdc.edu"],
  ["Valencia College", "Orlando, FL", "valenciacollege.edu"],
  ["Broward College", "Fort Lauderdale, FL", "broward.edu"],
  ["Houston Community College", "Houston, TX", "hccs.edu"],
  ["Austin Community College", "Austin, TX", "austincc.edu"],
  ["Lone Star College", "The Woodlands, TX", "lonestar.edu"],
  ["Dallas College", "Dallas, TX", "dallascollege.edu"],
  ["Tarrant County College", "Fort Worth, TX", "tccd.edu"],
  ["Santa Monica College", "Santa Monica, CA", "smc.edu"],
  ["De Anza College", "Cupertino, CA", "deanza.edu"],
  ["Pasadena City College", "Pasadena, CA", "pasadena.edu"],
  ["East Los Angeles College", "Monterey Park, CA", "elac.edu"],
  ["Mt. San Antonio College", "Walnut, CA", "mtsac.edu"],
  ["Diablo Valley College", "Pleasant Hill, CA", "dvc.edu"],
  ["Foothill College", "Los Altos Hills, CA", "foothill.edu"],
  ["City College of San Francisco", "San Francisco, CA", "ccsf.edu"],
  ["Orange Coast College", "Costa Mesa, CA", "orangecoastcollege.edu"],
  ["Northern Virginia Community College", "Annandale, VA", "nvcc.edu"],
  ["Montgomery College", "Rockville, MD", "montgomerycollege.edu"],
  ["Community College of Philadelphia", "Philadelphia, PA", "ccp.edu"],
  ["Bergen Community College", "Paramus, NJ", "bergen.edu"],
  ["Borough of Manhattan Community College", "New York, NY", "bmcc.cuny.edu"],
  ["LaGuardia Community College", "Long Island City, NY", "laguardia.edu"],
  ["Nassau Community College", "Garden City, NY", "ncc.edu"],
  ["Bunker Hill Community College", "Boston, MA", "bhcc.edu"],
  ["Cuyahoga Community College", "Cleveland, OH", "tri-c.edu"],
  ["Sinclair Community College", "Dayton, OH", "sinclair.edu"],
  ["College of DuPage", "Glen Ellyn, IL", "cod.edu"],
  ["Harper College", "Palatine, IL", "harpercollege.edu"],
  ["Ivy Tech Community College", "Indianapolis, IN", "ivytech.edu"],
  ["Central Piedmont Community College", "Charlotte, NC", "cpcc.edu"],
  ["Wake Technical Community College", "Raleigh, NC", "waketech.edu"],
  ["Salt Lake Community College", "Salt Lake City, UT", "slcc.edu"],
  ["Portland Community College", "Portland, OR", "pcc.edu"],
  ["Seattle Central College", "Seattle, WA", "seattlecentral.edu"],
  ["Phoenix College", "Phoenix, AZ", "phoenixcollege.edu"],
  ["Mesa Community College", "Mesa, AZ", "mesacc.edu"],
  ["Community College of Denver", "Denver, CO", "ccd.edu"],
  ["Front Range Community College", "Westminster, CO", "frontrange.edu"],
];

export const US_UNIVERSITIES: UniversitySeed[] = raw.map(([name, city, emailDomain]) => ({
  name,
  country: "USA",
  city,
  emailDomain,
}));
