import {
  BookOpen,
  Laptop,
  Sofa,
  Shirt,
  Utensils,
  Dumbbell,
  Bike,
  Music2,
  Ticket,
  Gift,
  GraduationCap,
  Truck,
  Wrench,
  Camera,
  FileText,
  Car,
  PawPrint,
  Sparkles,
  CalendarDays,
  Scissors,
  Brush,
  Hand,
  ChefHat,
  PenTool,
  HeartPulse,
  Tag,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  laptop: Laptop,
  sofa: Sofa,
  shirt: Shirt,
  utensils: Utensils,
  dumbbell: Dumbbell,
  bike: Bike,
  music: Music2,
  ticket: Ticket,
  gift: Gift,
  "graduation-cap": GraduationCap,
  truck: Truck,
  wrench: Wrench,
  camera: Camera,
  "file-text": FileText,
  car: Car,
  "paw-print": PawPrint,
  sparkles: Sparkles,
  calendar: CalendarDays,
  scissors: Scissors,
  brush: Brush,
  hand: Hand,
  "chef-hat": ChefHat,
  "pen-tool": PenTool,
  "heart-pulse": HeartPulse,
};

export function getCategoryIcon(name: string): LucideIcon {
  return ICONS[name] ?? Tag;
}
